EXTRA_DIST = %D%/includes/WcalcController.h \
			 %D%/includes/AboutBoxController.h \
			 %D%/includes/ConversionList.h \
			 %D%/includes/ErrorController.h \
			 %D%/includes/HistoryList.h \
			 %D%/includes/InspectorController.h \
			 %D%/includes/MyTextField.h \
			 %D%/includes/OldVariableList.h \
			 %D%/includes/PersVarList.h \
			 %D%/includes/VariableList.h \
			 %D%/includes/WcalcService.h \
			 %D%/includes/theDelegate.h \
			 %D%/includes/simpleCalc.h \
			 %D%/WcalcController.m \
			 %D%/AboutBoxController.m \
			 %D%/ConversionList.m \
			 %D%/ErrorController.m \
			 %D%/HistoryList.m \
			 %D%/InspectorController.m \
			 %D%/MyTextField.m \
			 %D%/OldVariableList.m \
			 %D%/PersVarList.m \
			 %D%/VariableList.m \
			 %D%/WcalcService.m \
			 %D%/theDelegate.m \
			 %D%/main.m \
			 %D%/simpleCalc.c
# vim:ft=automake
