noinst_HEADERS = \
		 %D%/add_commas.h \
		 %D%/calculator.h \
		 %D%/conversion.h \
		 %D%/definitions.h \
		 %D%/evalvar.h \
		 %D%/explain.h \
		 %D%/extract_vars.h \
		 %D%/files.h \
		 %D%/historyManager.h \
		 %D%/iscmd.h \
		 %D%/isconst.h \
		 %D%/isfunc.h \
		 %D%/list.h \
		 %D%/number_formatting.h \
		 %D%/number.h \
		 %D%/output.h \
		 %D%/string_manip.h \
		 %D%/uint32_max.h \
		 %D%/variables.h
# vim:ft=automake
